#pragma config(Sensor, S4,     ,                    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma  platform(NXT)
#include "writeFile.c"


int error,errorant = 0;
int i = 1;

task main()
{
 SetSensorType(S1, sensorLightActive);
 i = 0;
 while(1){
   i=0;
   while((SensorValue(S4))>=70&&(i<=4000)){
    motor[motorA] = -30;
    motor[motorB] = 30;
    wait1Msec(1);
    i++;
   }
   while(SensorValue(S1)<=60){
    motor[motorA] = 60;
    motor[motorB] = 60;
   }

   i=0;
   if((SensorValue(S1))>=60){
    motor[motorA] = -60;
    motor[motorB] = -60;
    wait1Msec(50);
    while((SensorValue(S1))<=60&&(i<=2000)){
    wait1Msec(1);
    i++;
    }
   }

  /* motor[motorA] = -50;
   motor[motorB] = 50;
   wait1Msec(650);*/






/* error = 45 - SensorValue(S1); //valor 45 proveniente de una calibracion previa
 motor[motorA] = 65 + 2.1*error + 0.9*errorant;
 motor[motorB] = 40 - 1.4*error - 0.9*errorant;
 errorant=error;*/

  }
  }
