#pragma config(Sensor, S4,     ,                    sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma  platform(NXT)
#include "writeFile.c"


int i = 1;

task main()
{
 SetSensorType(S1, sensorLightActive);
 SetSensorType(S2, sensorTouch);//Derecho
 SetSensorType(S3, sensorTouch);//Izquierdo
  motor[motorC] = 100;
 i = 0;
 while(1){
   i=0;
   while((SensorValue(S4))>=70&&(i<=4000)&& SensorValue(S2)==0 && SensorValue(S3)==0){
    motor[motorA] = 25; 
    motor[motorB] = -25;
    wait1Msec(1);
    i++;
   }
   while(SensorValue(S1)<=60 && SensorValue(S2)==0 && SensorValue(S3)==0){
    motor[motorA] = 100;
    motor[motorB] = 100;
   }
   if(SensorValue(S2)==1) {
     motor[motorA] = 100;
     motor[motorB] = -100;
     wait1Msec(1000)
   }
   if(SensorValue(S3)==1) {
     motor[motorB] = 100;
     motor[motorA] = -100;
     wait1Msec(1000)
   }
    if((SensorValue(S1))>=60){
    motor[motorA] = -100;
    motor[motorB] = -100;
    wait1Msec(1300)
  }

	/*nxtDisplayTextLine(1,"%d" ,nMotorEncoder[motorC]);
	wait1Msec(1000);*/
  /* i=0;
   if((SensorValue(S1))>=60){
    motor[motorA] = -60;
    motor[motorB] = -60;
    wait1Msec(50);
    while((SensorValue(S1))<=60&&(i<=2000)){
    wait1Msec(1);
    i++;

    }
   }
 */
  }


  }
